/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "gpio.h"
#include "rcc.h"
#include "systick.h"
#include "systick.h"

int main(void)
{sysclock();
	GPIO_int(GPIOA,
		PIN_5, MODER_OUTPUT,
		OTYPER_PUSHPULL,
		OSPEEDR_LOW,
		PUPDR_NO );
systick_init(8000000 , 15);

	while(1){

		/*GPIO_Write(GPIOA ,
				PIN_5,
				PIN_STATE_SET);

		systick_delay(500);
		GPIO_Write(GPIOA ,
						PIN_5,
						PIN_STATE_RESET);
		systick_delay(500);
*/

	}
}
